import Link from "next/link";
import { ArrowRight, BadgeCheck, CircleDollarSign, Crosshair, Gamepad2, ShieldCheck, Sparkles, Trophy, Users } from "lucide-react";
import { Navbar, Footer, PageHeader, Card, ArrowLink } from "@/components/ui";
import { TournamentCard } from "@/components/tournament-card";
import { tournaments } from "@/lib/data";
const stats=[['24K+','Active competitors'],['1,280','Live tournaments'],['₹8.4Cr','Prizes paid out'],['99.9%','Platform uptime']];
export default function Home(){return <><Navbar/><main><section className="relative overflow-hidden px-5 pb-16 pt-20 md:pb-24 md:pt-28"><div className="absolute left-1/2 top-0 -z-10 h-[30rem] w-[30rem] -translate-x-1/2 rounded-full bg-electric/20 blur-[110px]"/><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-cyan/20 bg-cyan/5 px-3 py-1.5 text-xs font-bold text-cyan"><Sparkles size={14}/> THE ARENA AWAITS</div><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[.95] tracking-tight sm:text-6xl lg:text-7xl">Play hard.<br/><span className="bg-gradient-to-r from-cyan to-blue-500 bg-clip-text text-transparent">Rise higher.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">The competition platform built for serious players. Enter tournaments, build your squad, and turn your skill into a legacy.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/tournaments" className="btn-primary px-6 py-3.5">Explore tournaments <ArrowRight size={18}/></Link><Link href="/dashboard" className="btn-secondary px-6 py-3.5">View dashboard</Link></div><div className="mt-9 flex items-center gap-5 text-sm text-slate-400"><span className="flex items-center gap-1.5"><ShieldCheck className="text-success" size={17}/> Verified payouts</span><span className="flex items-center gap-1.5"><Users className="text-cyan" size={17}/> 24k competitors</span></div></div><div className="relative mx-auto w-full max-w-lg"><div className="panel overflow-hidden border-cyan/20 p-1 shadow-glow"><div className="rounded-[.9rem] bg-gradient-to-br from-slate-900 via-blue-950 to-slate-950 p-7"><div className="flex justify-between"><span className="eyebrow">LIVE NOW</span><span className="rounded-full bg-danger/15 px-2 py-1 text-[10px] font-bold text-red-400">● 4,821 WATCHING</span></div><h2 className="mt-12 text-3xl font-black">VALORANT<br/>CHAMPIONSHIP</h2><div className="mt-7 flex items-center justify-between border-y border-white/10 py-4 text-sm"><div><p className="font-bold">NOVA PRIME</p><p className="text-xs text-slate-400">#2 GLOBAL</p></div><span className="text-xl font-black text-cyan">VS</span><div className="text-right"><p className="font-bold">ECLIPSE</p><p className="text-xs text-slate-400">#5 GLOBAL</p></div></div><p className="mt-5 text-sm text-slate-400">Grand Final · Map 3 of 5</p></div></div><div className="absolute -bottom-5 -left-8 panel px-4 py-3 text-sm"><p className="text-xs text-slate-400">Prize pool</p><p className="font-black text-cyan">₹5,00,000</p></div></div></div></section>
<section className="mx-auto max-w-7xl px-5"><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-4">{stats.map(([n,l])=><div className="bg-ink px-5 py-6 text-center" key={l}><p className="text-2xl font-black text-white">{n}</p><p className="mt-1 text-xs text-slate-500">{l}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-5 pt-24"><div className="flex items-end justify-between"><PageHeader eyebrow="Compete today" title="Featured tournaments"/><ArrowLink href="/tournaments">View all</ArrowLink></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tournaments.map(t=><TournamentCard key={t.id} t={t}/>)}</div></section>
<section className="mx-auto max-w-7xl px-5 pt-24"><PageHeader eyebrow="Everything you need" title="Built to make competition better"/><div className="grid gap-5 md:grid-cols-3">{[[Trophy,'Play for real stakes','From casual cups to major championships, every match counts.'],[Users,'Find your squad','Build a team, recruit proven players, and grow together.'],[CircleDollarSign,'Fast, transparent payouts','Secure wallet, multiple payment options, and complete transaction history.']].map(([I,title,text])=>{const Icon=I as typeof Trophy;return <Card className="p-6" key={title as string}><div className="grid h-11 w-11 place-items-center rounded-xl bg-electric/15 text-cyan"><Icon/></div><h3 className="mt-5 text-lg font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text as string}</p></Card>})}</div></section>
<section className="mx-auto max-w-7xl px-5 pt-24"><Card className="relative overflow-hidden bg-gradient-to-r from-blue-950/70 to-slate-900 p-8 md:p-12"><Crosshair className="absolute -right-8 -top-8 h-48 w-48 text-cyan/10"/><p className="eyebrow">START YOUR CLIMB</p><h2 className="mt-3 max-w-lg text-3xl font-black md:text-4xl">Your next great match is one click away.</h2><p className="mt-3 max-w-md text-slate-400">Create your player profile and enter a competition made for your level.</p><Link href="/register" className="btn-primary mt-6">Create free account <ArrowRight size={17}/></Link></Card></section></main><Footer/></>}
